config:
  port: 6666
  executorCount: 1
jobs:
  testingStuff:
    source: https://github.com/CoucouInc/lambdaCoucou.git
    steps:
      # - run: stack build
      - run: echo "foo"
      - run:
          name: echoing stuff
          command: echo "bar"
      - run:
          name: fail
          command: nope
